
;;
;; This color-theme was generated online using
;;      http://vic.github.com/color-theme 
;;
;; name: color-theme-dark
;; date: Wed Aug 11 2010 05:55:23 GMT-0500 (CDT)
;;
;;
;; To use this theme save this code to a file named:
;;     color-theme-dark.el
;;
;; Place it on a directory in your load-path
;; and put the following on your init-file: 
;;
;;     (require 'color-theme-dark)
;;     (color-theme-dark)
;;


(defun color-theme-dark ()
  "Default Emacs colors in dark background."
  (interactive)
  (color-theme-install
    '(color-theme-dark
      (
       (background-color . "black")
       (background-mode . "dark")
       (border-color . "black")
       (cursor-color . "#141312")
       (foreground-color . "white")
       (mouse-color . "#141312")
      )
      (
       (Man-overstrike-face . "bold")
       (Man-reverse-face . "highlight")
       (Man-underline-face . "underline")
       (align-highlight-change-face . "highlight")
       (align-highlight-nochange-face . "secondary-selection")
       (compilation-message-face . "underline")
       (list-matching-lines-buffer-name-face . "underline")
       (list-matching-lines-face . "match")
       (org-goto-interface . "outline")
       (term-default-bg-color . "black")
       (term-default-fg-color . "white")
       (view-highlight-face . "highlight")
       (widget-mouse-face . "highlight")
      )
      (default  ((t (:stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
      (antlr-default  ((t (:null nil))))
      (antlr-keyword  ((t (:foreground "Cyan1"))))
      (antlr-literal  ((t (:foreground "LightSalmon"))))
      (antlr-ruledef  ((t (:foreground "LightSkyBlue"))))
      (antlr-ruleref  ((t (:foreground "PaleGreen"))))
      (antlr-syntax  ((t (:foreground "Aquamarine"))))
      (antlr-tokendef  ((t (:foreground "LightSkyBlue"))))
      (antlr-tokenref  ((t (:foreground "PaleGreen"))))
      (bold  ((t (:bold t :weight bold))))
      (bold-italic  ((t (:italic t :slant italic :weight bold))))
      (border  ((t (:null nil))))
      (buffer-menu-buffer  ((t (:bold t :weight bold))))
      (button  ((t (:underline t))))
      (c-nonbreakable-space-face  ((t (:bold t :background "Pink" :weight bold))))
      (comint-highlight-input  ((t (:bold t :weight bold))))
      (comint-highlight-prompt  ((t (:foreground "cyan1"))))
      (compilation-column-number  ((t (:foreground "PaleGreen"))))
      (compilation-error  ((t (:bold t :weight bold :foreground "Pink"))))
      (compilation-info  ((t (:bold t :foreground "Green1" :weight bold))))
      (compilation-line-number  ((t (:foreground "LightGoldenrod"))))
      (compilation-warning  ((t (:bold t :foreground "Orange" :weight bold))))
      (completions-common-part  ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "white" :background "black" :stipple nil :height 120))))
      (completions-first-difference  ((t (:bold t :weight bold))))
      (cursor  ((t (:null nil))))
      (diff-added  ((t (:null nil))))
      (diff-changed  ((t (:null nil))))
      (diff-context  ((t (:foreground "grey70"))))
      (diff-file-header  ((t (:bold t :background "grey60" :weight bold))))
      (diff-function  ((t (:background "grey45"))))
      (diff-header  ((t (:background "grey45"))))
      (diff-hunk-header  ((t (:background "grey45"))))
      (diff-index  ((t (:bold t :weight bold :background "grey60"))))
      (diff-indicator-added  ((t (:null nil))))
      (diff-indicator-changed  ((t (:null nil))))
      (diff-indicator-removed  ((t (:null nil))))
      (diff-nonexistent  ((t (:bold t :weight bold :background "grey60"))))
      (diff-refine-change  ((t (:background "grey60"))))
      (diff-removed  ((t (:null nil))))
      (dired-directory  ((t (:foreground "LightSkyBlue"))))
      (dired-flagged  ((t (:bold t :weight bold :foreground "Pink"))))
      (dired-header  ((t (:foreground "PaleGreen"))))
      (dired-ignored  ((t (:foreground "grey70"))))
      (dired-mark  ((t (:foreground "Aquamarine"))))
      (dired-marked  ((t (:bold t :weight bold :foreground "Pink"))))
      (dired-perm-write  ((t (:foreground "chocolate1"))))
      (dired-symlink  ((t (:foreground "Cyan1"))))
      (dired-warning  ((t (:bold t :weight bold :foreground "Pink"))))
      (eldoc-highlight-function-argument  ((t (:bold t :weight bold))))
      (escape-glyph  ((t (:foreground "cyan"))))
      (eshell-ls-archive  ((t (:bold t :foreground "Orchid" :weight bold))))
      (eshell-ls-backup  ((t (:foreground "LightSalmon"))))
      (eshell-ls-clutter  ((t (:bold t :foreground "OrangeRed" :weight bold))))
      (eshell-ls-directory  ((t (:bold t :foreground "SkyBlue" :weight bold))))
      (eshell-ls-executable  ((t (:bold t :foreground "Green" :weight bold))))
      (eshell-ls-missing  ((t (:bold t :foreground "Red" :weight bold))))
      (eshell-ls-product  ((t (:foreground "LightSalmon"))))
      (eshell-ls-readonly  ((t (:foreground "Pink"))))
      (eshell-ls-special  ((t (:bold t :foreground "Magenta" :weight bold))))
      (eshell-ls-symlink  ((t (:bold t :foreground "Cyan" :weight bold))))
      (eshell-ls-unreadable  ((t (:foreground "DarkGrey"))))
      (eshell-prompt  ((t (:bold t :foreground "Pink" :weight bold))))
      (file-name-shadow  ((t (:foreground "grey70"))))
      (fixed-pitch  ((t (:family "Monospace"))))
      (font-lock-builtin-face  ((t (:foreground "LightSteelBlue"))))
      (font-lock-comment-delimiter-face  ((t (:foreground "chocolate1"))))
      (font-lock-comment-face  ((t (:foreground "chocolate1"))))
      (font-lock-constant-face  ((t (:foreground "Aquamarine"))))
      (font-lock-doc-face  ((t (:foreground "LightSalmon"))))
      (font-lock-function-name-face  ((t (:foreground "LightSkyBlue"))))
      (font-lock-keyword-face  ((t (:foreground "Cyan1"))))
      (font-lock-negation-char-face  ((t (:null nil))))
      (font-lock-preprocessor-face  ((t (:foreground "LightSteelBlue"))))
      (font-lock-regexp-grouping-backslash  ((t (:bold t :weight bold))))
      (font-lock-regexp-grouping-construct  ((t (:bold t :weight bold))))
      (font-lock-string-face  ((t (:foreground "LightSalmon"))))
      (font-lock-type-face  ((t (:foreground "PaleGreen"))))
      (font-lock-variable-name-face  ((t (:foreground "LightGoldenrod"))))
      (font-lock-warning-face  ((t (:bold t :foreground "Pink" :weight bold))))
      (fringe  ((t (:background "grey10"))))
      (header-line  ((t (:box nil :background "grey20" :foreground "grey90"))))
      (help-argument-name  ((t (:italic t :slant italic))))
      (highlight  ((t (:background "darkolivegreen"))))
      (ido-first-match  ((t (:bold t :weight bold))))
      (ido-incomplete-regexp  ((t (:bold t :weight bold :foreground "Pink"))))
      (ido-indicator  ((t (:background "red1" :foreground "yellow1" :width condensed))))
      (ido-only-match  ((t (:foreground "ForestGreen"))))
      (ido-subdir  ((t (:foreground "red1"))))
      (info-header-node  ((t (:italic t :weight bold :slant italic :foreground "white"))))
      (info-header-xref  ((t (:foreground "cyan1" :underline t))))
      (info-menu-header  ((t (:bold t :family "Sans Serif" :weight bold))))
      (info-menu-star  ((t (:foreground "red1"))))
      (info-node  ((t (:italic t :foreground "white" :slant italic :weight bold))))
      (info-title-1  ((t (:bold t :weight bold :family "Sans Serif" :height 1.728))))
      (info-title-2  ((t (:bold t :family "Sans Serif" :weight bold :height 1.44))))
      (info-title-3  ((t (:bold t :weight bold :family "Sans Serif" :height 1.2))))
      (info-title-4  ((t (:bold t :family "Sans Serif" :weight bold))))
      (info-xref  ((t (:underline t :foreground "cyan1"))))
      (info-xref-visited  ((t (:null nil))))
      (isearch  ((t (:background "palevioletred2" :foreground "brown4"))))
      (isearch-fail  ((t (:background "red4"))))
      (italic  ((t (:italic t :slant italic))))
      (lazy-highlight  ((t (:background "paleturquoise4"))))
      (link  ((t (:foreground "cyan1" :underline t))))
      (link-visited  ((t (:underline t :foreground "violet"))))
      (match  ((t (:background "RoyalBlue3"))))
      (menu  ((t (:null nil))))
      (minibuffer-prompt  ((t (:foreground "cyan"))))
      (mode-line  ((t (:background "grey75" :foreground "black" :box ( :line-width -1 :style released-button )))))
      (mode-line-buffer-id  ((t (:bold t :weight bold))))
      (mode-line-emphasis  ((t (:bold t :weight bold))))
      (mode-line-highlight  ((t (:box ( :line-width 2,color,grey40,style,released-button )))))
      (mode-line-inactive  ((t (:background "grey30" :foreground "grey80" :box ( :line-width -1 :color "grey40" :style nil ) :weight light))))
      (mouse  ((t (:null nil))))
      (next-error  ((t (:background "blue3"))))
      (nobreak-space  ((t (:foreground "cyan" :underline t))))
      (org-agenda-column-dateline  ((t (:family "DejaVu Sans Mono" :weight normal :slant normal :underline nil :strike-through nil :background "grey30" :height 120))))
      (org-agenda-date  ((t (:foreground "LightSkyBlue"))))
      (org-agenda-date-weekend  ((t (:bold t :foreground "LightSkyBlue" :weight bold))))
      (org-agenda-dimmed-todo-face  ((t (:foreground "grey50"))))
      (org-agenda-restriction-lock  ((t (:background "skyblue4"))))
      (org-agenda-structure  ((t (:foreground "LightSkyBlue"))))
      (org-archived  ((t (:foreground "grey70"))))
      (org-clock-overlay  ((t (:background "SkyBlue4"))))
      (org-code  ((t (:foreground "grey70"))))
      (org-column  ((t (:background "grey30" :strike-through nil :underline nil :slant normal :weight normal :height 120 :family "DejaVu Sans Mono"))))
      (org-column-title  ((t (:bold t :background "grey30" :underline t :weight bold))))
      (org-date  ((t (:foreground "Cyan" :underline t))))
      (org-done  ((t (:bold t :foreground "PaleGreen" :weight bold))))
      (org-drawer  ((t (:foreground "LightSkyBlue"))))
      (org-ellipsis  ((t (:foreground "LightGoldenrod" :underline t))))
      (org-footnote  ((t (:foreground "Cyan" :underline t))))
      (org-formula  ((t (:foreground "chocolate1"))))
      (org-headline-done  ((t (:foreground "LightSalmon"))))
      (org-hide  ((t (:foreground "black"))))
      (org-latex-and-export-specials  ((t (:foreground "burlywood"))))
      (org-level-1  ((t (:foreground "LightSkyBlue"))))
      (org-level-2  ((t (:foreground "LightGoldenrod"))))
      (org-level-3  ((t (:foreground "Cyan1"))))
      (org-level-4  ((t (:foreground "chocolate1"))))
      (org-level-5  ((t (:foreground "PaleGreen"))))
      (org-level-6  ((t (:foreground "Aquamarine"))))
      (org-level-7  ((t (:foreground "LightSteelBlue"))))
      (org-level-8  ((t (:foreground "LightSalmon"))))
      (org-link  ((t (:foreground "Cyan" :underline t))))
      (org-property-value  ((t (:null nil))))
      (org-scheduled  ((t (:foreground "PaleGreen"))))
      (org-scheduled-previously  ((t (:foreground "chocolate1"))))
      (org-scheduled-today  ((t (:foreground "PaleGreen"))))
      (org-sexp-date  ((t (:foreground "Cyan"))))
      (org-special-keyword  ((t (:foreground "LightSalmon"))))
      (org-table  ((t (:foreground "LightSkyBlue"))))
      (org-tag  ((t (:bold t :weight bold))))
      (org-target  ((t (:underline t))))
      (org-time-grid  ((t (:foreground "LightGoldenrod"))))
      (org-todo  ((t (:bold t :foreground "Pink" :weight bold))))
      (org-upcoming-deadline  ((t (:foreground "chocolate1"))))
      (org-verbatim  ((t (:foreground "grey70" :underline t))))
      (org-warning  ((t (:bold t :weight bold :foreground "Pink"))))
      (outline-1  ((t (:foreground "LightSkyBlue"))))
      (outline-2  ((t (:foreground "LightGoldenrod"))))
      (outline-3  ((t (:foreground "Cyan1"))))
      (outline-4  ((t (:foreground "chocolate1"))))
      (outline-5  ((t (:foreground "PaleGreen"))))
      (outline-6  ((t (:foreground "Aquamarine"))))
      (outline-7  ((t (:foreground "LightSteelBlue"))))
      (outline-8  ((t (:foreground "LightSalmon"))))
      (query-replace  ((t (:foreground "brown4" :background "palevioletred2"))))
      (region  ((t (:background "blue3"))))
      (scroll-bar  ((t (:null nil))))
      (secondary-selection  ((t (:background "SkyBlue4"))))
      (sgml-namespace  ((t (:foreground "LightSteelBlue"))))
      (shadow  ((t (:foreground "grey70"))))
      (subscript  ((t (:height tex-suscript-height))))
      (superscript  ((t (:height tex-suscript-height))))
      (tex-math  ((t (:foreground "LightSalmon"))))
      (tex-verbatim  ((t (:family "courier"))))
      (tool-bar  ((t (:background "grey75" :foreground "black" :box ( :line-width t :style released-button )))))
      (tooltip  ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
      (trailing-whitespace  ((t (:background "red1"))))
      (underline  ((t (:underline t))))
      (variable-pitch  ((t (:family "Sans Serif"))))
      (vertical-border  ((t (:null nil))))
      (which-func  ((t (:foreground "Blue1"))))
      (widget-button  ((t (:bold t :weight bold))))
      (widget-button-pressed  ((t (:foreground "red1"))))
      (widget-documentation  ((t (:foreground "lime green"))))
      (widget-field  ((t (:background "dim gray"))))
      (widget-inactive  ((t (:foreground "grey70"))))
      (widget-single-line-field  ((t (:background "dim gray"))))
    )
  )
)
