
(require 'color-theme)

(defun color-theme-dark-vee ()
  "Color theme by vic, created 2006-05-05."
  (interactive)
  (color-theme-install
   '(color-theme-dark-vee
     ((background-color . "#000200")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "cyan")
      (foreground-color . "navajo white")
      (mouse-color . "cyan")
      (viper-saved-cursor-color-in-replace-mode . "cyan"))
     ((goto-address-mail-face . italic)
      (goto-address-mail-mouse-face . secondary-selection)
      (goto-address-url-face . bold)
      (goto-address-url-mouse-face . highlight)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (rmail-highlight-face . rmail-highlight)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal ))))
     (Buffer-menu-buffer-face ((t (:bold t :weight bold))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (:background "black"))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (c-nonbreakable-space-face ((t (:background "red2" :box (:line-width 1 :color "red4")))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan1"))))
     (completions-common-part ((t (:stipple nil :background "#000800" :foreground "navajo white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width semi-condensed))))
     (completions-first-difference ((t (:bold t :foreground "aquamarine" :weight bold))))
     (cursor ((t (:background "cyan"))))
     (custom-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-face ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-face ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:underline t :foreground "violet"))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-changed-face ((t (:background "blue1" :foreground "white"))))
     (custom-comment ((t (:background "dim gray"))))
     (custom-comment-face ((t (:background "dim gray"))))
     (custom-comment-tag ((t (:foreground "gray80"))))
     (custom-comment-tag-face ((t (:foreground "gray80"))))
     (custom-documentation ((t (nil))))
     (custom-documentation-face ((t (nil))))
     (custom-face-tag ((t (:bold t :weight bold ))))
     (custom-face-tag-face ((t (:bold t :weight bold ))))
     (custom-group-tag ((t (:bold t :foreground "light blue" :weight bold ))))
     (custom-group-tag-1 ((t (:bold t :foreground "pink" :weight bold ))))
     (custom-group-tag-face ((t (:bold t :foreground "light blue" :weight bold ))))
     (custom-group-tag-face-1 ((t (:bold t :foreground "pink" :weight bold ))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-invalid-face ((t (:background "red1" :foreground "yellow1"))))
     (custom-link ((t (:underline t :foreground "cyan1"))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-modified-face ((t (:background "blue1" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-rogue-face ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-saved-face ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-set-face ((t (:background "white" :foreground "blue1"))))
     (custom-state ((t (:foreground "lime green"))))
     (custom-state-face ((t (:foreground "lime green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-button-face ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:bold t :foreground "light blue" :weight bold ))))
     (custom-variable-tag-face ((t (:bold t :foreground "light blue" :weight bold ))))
     (elscreen-tab-background-face ((t (:background "Gray50"))))
     (elscreen-tab-current-screen-face ((t (:background "white" :foreground "black"))))
     (elscreen-tab-other-screen-face ((t (:background "Gray85" :foreground "Gray50"))))
     (escape-glyph ((t (:foreground "cyan"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (font-lock-builtin-face ((t (:foreground "DarkSeaGreen2"))))
     (font-lock-comment-delimiter-face ((t (:italic t :foreground "DarkOrange" :slant oblique ))))
     (font-lock-comment-face ((t (:foreground "Azure3" ))))
     (font-lock-constant-face ((t (:foreground "Aquamarine"))))
     (font-lock-doc-face ((t (:foreground "AntiqueWhite4" ))))
     (font-lock-doc-string-face ((t (:foreground "AntiqueWhite3" ))))
     (font-lock-function-name-face ((t (:foreground "Aquamarine" :width ultra-condensed))))
     (font-lock-keyword-face ((t (:foreground "salmon" ))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "peru" :width condensed))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "sandybrown"))))
     (font-lock-type-face ((t (:foreground "PaleGreen1"))))
     (font-lock-variable-name-face ((t (:foreground "Aquamarine" :weight ultra-light))))
     (font-lock-warning-face ((t (:foreground "red2" :box (:line-width 1 :color "red4")))))
     (fringe ((t (:italic t :background "#000800" :foreground "DarkSeaGreen2" :slant oblique ))))
     (header-line ((t (:box (:line-width 1 :style released-button)))))
     (help-argument-name ((t (:italic t :slant italic))))
     (highlight ((t (:background "darkolivegreen"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-first-match-face ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:box (:line-width 1 :color "red4") :foreground "red2"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-indicator-face ((t (:foreground "yellow" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-only-match-face ((t (:foreground "green"))))
     (ido-subdir ((t (:foreground "red1"))))
     (ido-subdir-face ((t (:foreground "turquoise"))))
     (isearch ((t (:italic t :background "DarkOliveGreen4" :foreground "DarkOliveGreen2" :slant oblique))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "DarkSeaGreen4" :foreground "DarkSeaGreen2"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (match ((t (:background "RoyalBlue4"))))
     (menu ((t (nil))))
     (minibuffer-prompt ((t (:italic t :foreground "pale green" :slant oblique ))))
     (mode-line-highlight ((t (:background "light sky blue" :foreground "black" ))))
     (mode-line-inactive ((t (:background "#000500" :foreground "#5A6929" ))))
     (mode-line-buffer-id ((t (:weight bold :slant oblique))))
     (mode-line ((t (:background "#000800" :foreground "#9CCF5A" :overline "#182410" :underline "#182410" ))))
     (mouse ((t (:background "plum3" :slant oblique))))
     (next-error ((t (:background "blue3"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (paren-face-match ((t (:background "turquoise"))))
     (paren-face-mismatch ((t (:background "purple" :foreground "white"))))
     (paren-face-no-match ((t (:background "yellow" :foreground "black"))))
     (query-replace ((t (:italic t :background "DarkOliveGreen4" :foreground "DarkOliveGreen2" :slant oblique))))
     (region ((t (:background "#001100"))))
     (scroll-bar ((t (:background "grey75" :foreground "#cccccc"))))
     (secondary-selection ((t (:background "SkyBlue4"))))
     (semantic-dirty-token-face ((t (:background "#151C0E"))))
     (shadow ((t (:foreground "grey70"))))
     (show-paren-match ((t (:background "steelblue3"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (strokes-char ((t (:background "lightgray"))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:strike-through "#2A391C"))))
     (underline ((t (:underline t))))
     (vertical-border ((t (nil))))
     (viper-insert-face ((t (:background "#263319"))))
     (viper-minibuffer-emacs ((t nil)))
     (viper-minibuffer-insert-face ((t (:background "pink" :foreground "Black"))))
     (viper-minibuffer-vi-face ((t (:background "grey" :foreground "DarkGreen"))))
     (viper-replace-overlay-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-search-face ((t (:background "khaki" :foreground "Black"))))
     (w3m-anchor-face ((t (:foreground "#96CD66" :weight ultra-light))))
     (w3m-arrived-anchor-face ((t (:foreground "#96CD66" :underline t :weight ultra-light))))
     (w3m-form-face ((t (:foreground "DarkSlateGray4" :underline t))))
     (w3m-tab-background-face ((t (:stipple nil :background "#000800" :foreground "navajo white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width semi-condensed ))))
     (w3m-tab-selected-face ((t (:background "#1C2613" :foreground "#6B9047"))))
     (w3m-tab-selected-retrieving-face ((t (:background "#1C2613" :foreground "#6B9047" :underline "green"))))
     (w3m-tab-unselected-face ((t (:background "#001600" :foreground "#384A24"))))
     (w3m-tab-unselected-retrieving-face ((t (:background "#001600" :foreground "#384A24" :underline "Green3"))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray"))))
     (widget-inactive ((t (:foreground "light gray"))))
     (widget-single-line-field ((t (:background "dim gray"))))
     (wn-modeline-face ((t (:foreground "#9CCF5A" :background "#101810" :box (:line-width 1 :color "#030803" :style pressed-button))))))))

(defalias 'vee/color-theme-dark-vee #'color-theme-dark-vee)
(provide 'vee/color-theme-dark-vee)
